// File: Components/BreedData.js
export const BREEDS = [
  {
    id: 'bengal',
    name: 'Bengal',
    originRegion: 'North America',
    regionLatLng: { lat: 37.09, lng: -95.71 },
    coatType: 'short',
    temperament: ['Playful', 'Active', 'Curious', 'Athletic'],
    sheddingLevel: 3,
    groomingPerWeek: 2,
    dailyPlayMin: 60,
    weightKgMin: 3.6,
    weightKgMax: 7.0,
    lifespanYearsMin: 12,
    lifespanYearsMax: 16,
    descriptionShort:
      'Athletic wild-looking cats with leopard-like spots. Highly energetic, love water and climbing.',
    careTips: [
      'Provide puzzle feeders and interactive toys.',
      'Leash train early for outdoor exploration.',
      'Supplement with omega-3 for coat health.',
      'Rotate toys weekly to prevent boredom.',
    ],
    imageKey: 'breed_bengal',
  },
  {
    id: 'mainecoon',
    name: 'Maine Coon',
    originRegion: 'North America',
    regionLatLng: { lat: 44.69, lng: -69.38 },
    coatType: 'long',
    temperament: ['Gentle', 'Playful', 'Sociable', 'Dog-like'],
    sheddingLevel: 4,
    groomingPerWeek: 5,
    dailyPlayMin: 40,
    weightKgMin: 4.0,
    weightKgMax: 9.0,
    lifespanYearsMin: 12,
    lifespanYearsMax: 15,
    descriptionShort:
      'One of the largest domestic breeds. Friendly giants with tufted ears and a bushy tail.',
    careTips: [
      'Brush 3-5 times per week to prevent mats.',
      'Check ears weekly for wax buildup.',
      'Provide a tall, sturdy cat tree.',
      'Schedule annual cardiac screening.',
    ],
    imageKey: 'breed_mainecoon',
  },
  {
    id: 'siamese',
    name: 'Siamese',
    originRegion: 'Asia',
    regionLatLng: { lat: 13.76, lng: 100.5 },
    coatType: 'short',
    temperament: ['Vocal', 'Social', 'Intelligent', 'Demanding'],
    sheddingLevel: 2,
    groomingPerWeek: 1,
    dailyPlayMin: 45,
    weightKgMin: 2.5,
    weightKgMax: 5.5,
    lifespanYearsMin: 15,
    lifespanYearsMax: 20,
    descriptionShort:
      'One of the oldest recognized breeds. Highly vocal and deeply bonded to their owners.',
    careTips: [
      'Provide daily interactive play to satisfy intelligence.',
      'Avoid leaving alone for long periods.',
      'Weekly brush keeps the short coat shiny.',
      'Regular dental care is important.',
    ],
    imageKey: 'breed_siamese',
  },
  {
    id: 'british',
    name: 'British Shorthair',
    originRegion: 'Europe',
    regionLatLng: { lat: 51.5, lng: -0.12 },
    coatType: 'short',
    temperament: ['Calm', 'Independent', 'Affectionate', 'Easygoing'],
    sheddingLevel: 3,
    groomingPerWeek: 2,
    dailyPlayMin: 20,
    weightKgMin: 3.0,
    weightKgMax: 7.7,
    lifespanYearsMin: 12,
    lifespanYearsMax: 20,
    descriptionShort:
      'Chunky and calm, the British Shorthair adapts well to apartment life and busy families.',
    careTips: [
      'Twice-weekly brushing prevents shedding.',
      'Monitor weight — prone to obesity.',
      'Dental hygiene check monthly.',
      'Provide floor-level perches.',
    ],
    imageKey: 'breed_british',
  },
  {
    id: 'persian',
    name: 'Persian',
    originRegion: 'Asia',
    regionLatLng: { lat: 32.43, lng: 53.69 },
    coatType: 'long',
    temperament: ['Gentle', 'Quiet', 'Docile', 'Affectionate'],
    sheddingLevel: 5,
    groomingPerWeek: 7,
    dailyPlayMin: 15,
    weightKgMin: 3.0,
    weightKgMax: 5.9,
    lifespanYearsMin: 12,
    lifespanYearsMax: 17,
    descriptionShort:
      'Luxurious long coat, flat face, and a gentle disposition. Persians thrive indoors.',
    careTips: [
      'Daily brushing is essential to prevent matting.',
      'Wipe facial folds daily.',
      'Use a wide-toothed comb on the belly.',
      'Schedule eye-cleaning every morning.',
    ],
    imageKey: 'breed_persian',
  },
  {
    id: 'sphynx',
    name: 'Sphynx',
    originRegion: 'North America',
    regionLatLng: { lat: 43.65, lng: -79.38 },
    coatType: 'hairless',
    temperament: ['Extroverted', 'Playful', 'Mischievous', 'Warm'],
    sheddingLevel: 1,
    groomingPerWeek: 2,
    dailyPlayMin: 50,
    weightKgMin: 3.0,
    weightKgMax: 5.5,
    lifespanYearsMin: 8,
    lifespanYearsMax: 14,
    descriptionShort:
      'The hairless wonder. Sphynx cats are high-energy, skin-care-demanding, and people-oriented.',
    careTips: [
      'Weekly bath to remove skin oils.',
      'Keep warm in cool environments.',
      'Clean ears weekly.',
      'Apply pet-safe sunscreen before outdoor time.',
    ],
    imageKey: 'breed_sphynx',
  },
  {
    id: 'ragdoll',
    name: 'Ragdoll',
    originRegion: 'North America',
    regionLatLng: { lat: 34.05, lng: -118.24 },
    coatType: 'long',
    temperament: ['Docile', 'Gentle', 'Calm', 'Affectionate'],
    sheddingLevel: 3,
    groomingPerWeek: 3,
    dailyPlayMin: 25,
    weightKgMin: 4.5,
    weightKgMax: 9.0,
    lifespanYearsMin: 12,
    lifespanYearsMax: 17,
    descriptionShort:
      'They go limp when held — hence the name. Ragdolls are indoor companions with dog-like loyalty.',
    careTips: [
      'Brush twice weekly to keep coat silky.',
      'Avoid outdoor exposure — low street-sense.',
      'Cardiac screening recommended annually.',
      'Interactive wand toys for gentle play.',
    ],
    imageKey: 'breed_ragdoll',
  },
  {
    id: 'scottish',
    name: 'Scottish Fold',
    originRegion: 'Europe',
    regionLatLng: { lat: 56.49, lng: -4.2 },
    coatType: 'short',
    temperament: ['Sweet', 'Adaptable', 'Quiet', 'Loyal'],
    sheddingLevel: 3,
    groomingPerWeek: 2,
    dailyPlayMin: 30,
    weightKgMin: 2.7,
    weightKgMax: 6.0,
    lifespanYearsMin: 11,
    lifespanYearsMax: 15,
    descriptionShort:
      'Distinctive folded ears and round face. Scotties sit in the "Buddha pose" comically.',
    careTips: [
      'Monitor joints — susceptible to osteochondrodysplasia.',
      'Weekly ear cleaning around folds.',
      'Low-impact play to protect joints.',
      'Regular vet screening for joint issues.',
    ],
    imageKey: 'breed_scottish',
  },
  {
    id: 'abyssinian',
    name: 'Abyssinian',
    originRegion: 'Africa',
    regionLatLng: { lat: 9.02, lng: 38.74 },
    coatType: 'short',
    temperament: ['Active', 'Curious', 'Agile', 'Social'],
    sheddingLevel: 2,
    groomingPerWeek: 1,
    dailyPlayMin: 60,
    weightKgMin: 2.7,
    weightKgMax: 4.9,
    lifespanYearsMin: 9,
    lifespanYearsMax: 15,
    descriptionShort:
      'One of the oldest known breeds. Slender, agile, and endlessly curious about the world.',
    careTips: [
      'Provide tall cat trees and climbing walls.',
      'Daily interactive play sessions are a must.',
      'Monthly brushing keeps ticked coat vibrant.',
      'Check for hereditary blindness (PRA) early.',
    ],
    imageKey: 'breed_abyssinian',
  },
  {
    id: 'norwegian',
    name: 'Norwegian Forest',
    originRegion: 'Europe',
    regionLatLng: { lat: 60.47, lng: 8.47 },
    coatType: 'long',
    temperament: ['Independent', 'Gentle', 'Calm', 'Friendly'],
    sheddingLevel: 4,
    groomingPerWeek: 4,
    dailyPlayMin: 30,
    weightKgMin: 4.0,
    weightKgMax: 9.0,
    lifespanYearsMin: 14,
    lifespanYearsMax: 16,
    descriptionShort:
      'Built for Scandinavian winters with a dense double coat and strong climbing instincts.',
    careTips: [
      'Brush 3-4 times per week; daily in shedding season.',
      'Provide outdoor enclosure for enrichment.',
      'Screen for hypertrophic cardiomyopathy.',
      'High-protein diet supports muscle mass.',
    ],
    imageKey: 'breed_norwegian',
  },
  {
    id: 'russianblue',
    name: 'Russian Blue',
    originRegion: 'Europe',
    regionLatLng: { lat: 59.94, lng: 30.32 },
    coatType: 'short',
    temperament: ['Reserved', 'Intelligent', 'Loyal', 'Quiet'],
    sheddingLevel: 2,
    groomingPerWeek: 1,
    dailyPlayMin: 30,
    weightKgMin: 3.5,
    weightKgMax: 6.5,
    lifespanYearsMin: 15,
    lifespanYearsMax: 20,
    descriptionShort:
      'Bluish-silver coat and vivid green eyes. Reserved with strangers, devoted with family.',
    careTips: [
      'Weekly brushing maintains the dense plush coat.',
      'Establish a feeding routine — dislikes changes.',
      'Keep litter box pristine — fastidious by nature.',
      'Allow hiding spots for decompression.',
    ],
    imageKey: 'breed_russianblue',
  },
  {
    id: 'savannah',
    name: 'Savannah',
    originRegion: 'Africa',
    regionLatLng: { lat: -1.29, lng: 36.82 },
    coatType: 'short',
    temperament: ['Bold', 'Adventurous', 'Loyal', 'Energetic'],
    sheddingLevel: 2,
    groomingPerWeek: 1,
    dailyPlayMin: 90,
    weightKgMin: 5.0,
    weightKgMax: 11.0,
    lifespanYearsMin: 12,
    lifespanYearsMax: 20,
    descriptionShort:
      'Serval hybrid with tall ears and a spotted coat. One of the largest domestic cat breeds.',
    careTips: [
      'Needs large vertical spaces and catios.',
      'Leash walk daily for physical and mental stimulation.',
      'Raw or high-protein diet is preferred.',
      'Early socialization is critical.',
    ],
    imageKey: 'breed_savannah',
  },
];

export const REGIONS = [
  'North America',
  'Europe',
  'Asia',
  'Africa',
  'Australia',
  'South America',
];

export const REGION_COLORS = {
  'North America': '#6EA8FF',
  Europe: '#7C5CFF',
  Asia: '#FF5A7A',
  Africa: '#FFB347',
  Australia: '#2EE59D',
  'South America': '#5CE6D5',
};

export const COAT_TYPES = ['short', 'medium', 'long', 'hairless'];
